name: Continuous Integration and Deployment

on: 
    push:
        branches: 
            - main

env:  
    DOTNET-VERSION: '7.0.x'
    
jobs: 
    build:
        runs-on: ubuntu-latest
        steps: 
            - name: Check out code 🛎
              uses: actions/checkout@v3

            - name: Setpu .NET 
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: ${{ env.DOTNET-VERSION }}

            - name: Start SQL Server 
              run: |
                docker run -d -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=WeatherForeCast~Pass1" -e "MSSQL_PID=Express" -p 1433:1433 -d mcr.microsoft.com/mssql/server:2019-latest 

            - name: Sleep for 5 seconds 😴
              uses: jakejarvis/wait-action@master
              with:
               time: '5s'

            - name: Restore dependencies 🛠
              run: dotnet restore
              working-directory: WeatherForeCastAPI

            - name: Build App 🚀
              run: dotnet build -c Release --no-restore
              working-directory: WeatherForeCastAPI

            - name: Run automatted tests 🧪
              env:
                ConnectionString: Server=localhost; Database=CustomerDB_Test; User=sa; Password=WeatherForeCast~Pass1
              run: dotnet test
              working-directory: WeatherForeCast.Test

            - name: Publish app
              run: dotnet publish -c Release -o ./out
              working-directory: WeatherForeCastAPI
