name: Continuous Integration and Deployment

on: 
    push:
        branches: 
            - main
jobs: 
    build:
        runs-on: ubuntu-latest
        steps: 
            - name: Check out code 🛎
              uses: actions/checkout@v3

            - name: Setpu .NET 
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '7.0.x'

            - name: Restore dependencies 🛠
              run: dotnet restore
              working-directory: WeatherForeCastAPI

            - name: Build App 🚀
              run: dotnet build -c Release --no-restore
              working-directory: WeatherForeCastAPI

            - name: Run automatted tests 🧪
              run: dotnet test
              working-directory: WeatherForeCast.Test

            - name: Publish app
              run: dotnet publish -c Release -o ./out
